#!/usr/bin/env python3
"""Render deploy/ec2/.env from process environment (GitHub Actions secrets)."""

from __future__ import annotations

import os
import sys

# Required in GitHub Actions secrets
REQUIRED = (
    "DATABASE_URL",
    "EXTERNAL_ID_ENCRYPTION_KEY",
    "SUPABASE_URL",
)

# Optional secrets — omitted from file when empty
OPTIONAL = (
    "OIDC_JWT_SECRET",
    "OIDC_AUDIENCE",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_SESSION_TOKEN",
)

# Defaults for production EC2 + Docker Compose (override via env if needed)
DEFAULTS: dict[str, str] = {
    "REDIS_URL": "redis://redis:6379/0",
    "S3_BUCKET": "steampipe-data-storage",
    "S3_REGION": "us-east-1",
    "S3_PREFIX": "platform-v2",
    "USE_LOCAL_STORAGE": "false",
    "COLLECT_QUEUE_KEY": "platform:collect.aws",
    "PLATFORM_EVENTS_KEY": "platform:events",
    "POLICY_QUEUE_KEY": "platform:policy.evaluate",
    "API_HOST": "0.0.0.0",
    "API_PORT": "8090",
    "LOG_LEVEL": "INFO",
    "LOG_FORMAT": "json",
    "DEV_TENANT_HEADER_AUTH": "false",
    "OIDC_ENABLED": "true",
    "OIDC_AUDIENCE": "authenticated",
    "COLLECTOR_MOCK": "false",
    "AWS_DEFAULT_REGION": "us-east-1",
    "AWS_EC2_METADATA_DISABLED": "false",
    "CORS_ORIGINS": "https://app.drantiq.ai,https://admin.drantiq.ai",
}


def _escape_dotenv(value: str) -> str:
    if not value:
        return ""
    if any(c in value for c in " \t#\"'\n\\"):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    return value


def main() -> int:
    missing = [k for k in REQUIRED if not os.environ.get(k, "").strip()]
    if missing:
        print(f"Missing required env vars: {', '.join(missing)}", file=sys.stderr)
        return 1

    lines: list[str] = ["# Generated by GitHub Actions — do not edit on EC2 (overwritten each deploy)", ""]

    for key, default in DEFAULTS.items():
        val = os.environ.get(key, default).strip() or default
        lines.append(f"{key}={_escape_dotenv(val)}")

    for key in REQUIRED:
        val = os.environ.get(key, "").strip()
        if key in DEFAULTS:
            continue
        lines.append(f"{key}={_escape_dotenv(val)}")

    for key in OPTIONAL:
        val = os.environ.get(key, "").strip()
        if val:
            lines.append(f"{key}={_escape_dotenv(val)}")

    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
